/**
 * Built-in preset definitions covering different visual themes.
 */

import type { Preset } from './types';

export const builtInPresets: Preset[] = [
  {
    id: 'cyberpunk-bass',
    name: 'Cyberpunk Bass',
    description: 'Heavy bass-driven visuals with cyan and magenta neon',
    category: 'cyberpunk',
    sceneId: 'geometric-pulse',
    audioConfig: {
      sensitivity: 1.2,
      smoothing: 0.7,
      fftSize: 2048,
    },
    renderConfig: {
      bloom: true,
      bloomIntensity: 2.0,
      chromaticAberration: true,
      vignette: true,
      filmGrain: false,
    },
    cameraConfig: {
      mode: 'orbit',
      shakeIntensity: 0.3,
      orbitSpeed: 0.4,
      autoZoom: true,
    },
    colors: {
      primary: '#00ffff',
      secondary: '#ff00ff',
      accent: '#8b5cf6',
      background: '#0a0a0f',
    },
    createdAt: Date.now(),
    isFavorite: false,
    tags: ['bass', 'heavy', 'neon'],
  },
  {
    id: 'synthwave-dream',
    name: 'Synthwave Dream',
    description: 'Retro synthwave aesthetic with purple and pink gradients',
    category: 'synthwave',
    sceneId: 'infinite-tunnel',
    audioConfig: {
      sensitivity: 1.0,
      smoothing: 0.8,
      fftSize: 2048,
    },
    renderConfig: {
      bloom: true,
      bloomIntensity: 1.5,
      chromaticAberration: false,
      vignette: true,
      filmGrain: true,
    },
    cameraConfig: {
      mode: 'cinematic',
      shakeIntensity: 0.1,
      orbitSpeed: 0.2,
      autoZoom: false,
    },
    colors: {
      primary: '#a855f7',
      secondary: '#ec4899',
      accent: '#f97316',
      background: '#1a0a2e',
    },
    createdAt: Date.now(),
    isFavorite: false,
    tags: ['retro', 'smooth', '80s'],
  },
  {
    id: 'neon-pulse',
    name: 'Neon Pulse',
    description: 'Pulsing neon spectrum with vivid green and cyan',
    category: 'neon',
    sceneId: 'circular-spectrum',
    audioConfig: {
      sensitivity: 1.3,
      smoothing: 0.6,
      fftSize: 4096,
    },
    renderConfig: {
      bloom: true,
      bloomIntensity: 1.8,
      chromaticAberration: true,
      vignette: false,
      filmGrain: false,
    },
    cameraConfig: {
      mode: 'orbit',
      shakeIntensity: 0.15,
      orbitSpeed: 0.5,
      autoZoom: true,
    },
    colors: {
      primary: '#22c55e',
      secondary: '#06b6d4',
      accent: '#00ffcc',
      background: '#0a0f0a',
    },
    createdAt: Date.now(),
    isFavorite: false,
    tags: ['spectrum', 'reactive', 'bright'],
  },
  {
    id: 'space-odyssey',
    name: 'Space Odyssey',
    description: 'Cosmic space environment with subtle stellar effects',
    category: 'space',
    sceneId: 'space',
    audioConfig: {
      sensitivity: 0.8,
      smoothing: 0.85,
      fftSize: 2048,
    },
    renderConfig: {
      bloom: true,
      bloomIntensity: 1.2,
      chromaticAberration: false,
      vignette: true,
      filmGrain: false,
    },
    cameraConfig: {
      mode: 'cinematic',
      shakeIntensity: 0.05,
      orbitSpeed: 0.15,
      autoZoom: true,
    },
    colors: {
      primary: '#3b82f6',
      secondary: '#ffffff',
      accent: '#a855f7',
      background: '#050510',
    },
    createdAt: Date.now(),
    isFavorite: false,
    tags: ['space', 'ambient', 'cosmic'],
  },
  {
    id: 'edm-festival',
    name: 'EDM Festival',
    description: 'High energy festival visuals with dynamic color cycling',
    category: 'edm',
    sceneId: 'trap-nation-ring',
    audioConfig: {
      sensitivity: 1.5,
      smoothing: 0.5,
      fftSize: 2048,
    },
    renderConfig: {
      bloom: true,
      bloomIntensity: 2.5,
      chromaticAberration: true,
      vignette: false,
      filmGrain: false,
    },
    cameraConfig: {
      mode: 'orbit',
      shakeIntensity: 0.4,
      orbitSpeed: 0.6,
      autoZoom: true,
    },
    colors: {
      primary: '#f43f5e',
      secondary: '#8b5cf6',
      accent: '#06b6d4',
      background: '#0a0a0f',
    },
    createdAt: Date.now(),
    isFavorite: false,
    tags: ['edm', 'festival', 'high-energy'],
  },
  {
    id: 'minimal-zen',
    name: 'Minimal Zen',
    description: 'Clean minimal waveform with subdued tones',
    category: 'minimal',
    sceneId: 'neon-waveform',
    audioConfig: {
      sensitivity: 0.7,
      smoothing: 0.9,
      fftSize: 2048,
    },
    renderConfig: {
      bloom: false,
      bloomIntensity: 0.5,
      chromaticAberration: false,
      vignette: false,
      filmGrain: false,
    },
    cameraConfig: {
      mode: 'static',
      shakeIntensity: 0,
      orbitSpeed: 0,
      autoZoom: false,
    },
    colors: {
      primary: '#e5e7eb',
      secondary: '#9ca3af',
      accent: '#6b7280',
      background: '#111111',
    },
    createdAt: Date.now(),
    isFavorite: false,
    tags: ['minimal', 'clean', 'calm'],
  },
];
